
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package CompiladoresMuerte2.Sintactic;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int Or = 31;
  public static final int True = 49;
  public static final int Entero = 6;
  public static final int Coma = 46;
  public static final int End = 21;
  public static final int Llave_c = 43;
  public static final int Llave_a = 42;
  public static final int Increment = 38;
  public static final int If = 9;
  public static final int Equal = 34;
  public static final int Default = 13;
  public static final int Menor = 33;
  public static final int Else = 10;
  public static final int Decrement = 39;
  public static final int Break = 14;
  public static final int ReadInt = 23;
  public static final int Corchete_c = 45;
  public static final int Corchete_a = 44;
  public static final int Mayor = 32;
  public static final int Return = 20;
  public static final int While = 16;
  public static final int Int = 2;
  public static final int Parentesis_c = 41;
  public static final int Cadena = 7;
  public static final int Parentesis_a = 40;
  public static final int For = 15;
  public static final int P_coma = 47;
  public static final int EOF = 0;
  public static final int Function = 19;
  public static final int And = 30;
  public static final int error = 1;
  public static final int Switch = 11;
  public static final int False = 50;
  public static final int Mult = 28;
  public static final int Div = 29;
  public static final int Print = 22;
  public static final int Not_equal = 35;
  public static final int ReadString = 24;
  public static final int Case = 12;
  public static final int id = 8;
  public static final int Dos_puntos = 48;
  public static final int Mayor_equal = 36;
  public static final int Const = 5;
  public static final int String = 3;
  public static final int Resta = 26;
  public static final int Menor_equal = 37;
  public static final int Bool = 4;
  public static final int Suma = 25;
  public static final int Main = 17;
  public static final int Igual = 27;
  public static final int Procedure = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Int",
  "String",
  "Bool",
  "Const",
  "Entero",
  "Cadena",
  "id",
  "If",
  "Else",
  "Switch",
  "Case",
  "Default",
  "Break",
  "For",
  "While",
  "Main",
  "Procedure",
  "Function",
  "Return",
  "End",
  "Print",
  "ReadInt",
  "ReadString",
  "Suma",
  "Resta",
  "Igual",
  "Mult",
  "Div",
  "And",
  "Or",
  "Mayor",
  "Menor",
  "Equal",
  "Not_equal",
  "Mayor_equal",
  "Menor_equal",
  "Increment",
  "Decrement",
  "Parentesis_a",
  "Parentesis_c",
  "Llave_a",
  "Llave_c",
  "Corchete_a",
  "Corchete_c",
  "Coma",
  "P_coma",
  "Dos_puntos",
  "True",
  "False"
  };
}

